### ISSUE TITLE
Make individual about me pages for each group member

### ISSUE THREAD

**Issue by ashwinbabu888** [nolanplatt/AP-CSA-T2#18]
- [x] Special customization
- [x] Picture w/ mask + toggle to custom pic
- [x] Pull/show data with API
- [x] Links to journal or other work
- [x] Use database OR add dynamic links

**Comment by nolanplatt** [comment]
Partially completed with this (commit)[https://github.com/nolanplatt/AP-CSA-T2/commit/161c9514634d638384a75a0b5e53e17ea90ac56f]. Still needs to be completed with pictures, special customization, & journal link.
